<?php
include 'db.php';

if(!isset($_GET['id'])) { die("Access Denied"); }

$leave_id = mysqli_real_escape_string($conn, $_GET['id']);
$query = "SELECT leave_requests.*, users.fullname, users.role FROM leave_requests 
          JOIN users ON leave_requests.user_id = users.id 
          WHERE leave_requests.id = '$leave_id' AND status = 'approved'";
$result = mysqli_query($conn, $query);
$data = mysqli_fetch_assoc($result);

if(!$data) { die("Only approved leaves can be printed."); }
?>
<!DOCTYPE html>
<html>
<head>
    <title>Leave Approval Slip</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { background: white; padding: 50px; }
        .slip-border { border: 2px solid #000; padding: 30px; border-radius: 10px; }
        .seal { border: 1px dashed #ccc; width: 150px; height: 80px; margin-top: 20px; display: flex; align-items: center; justify-content: center; color: #ccc; }
        @media print { .no-print { display: none; } }
    </style>
</head>
<body onload="window.print()">
    <div class="container slip-border">
        <div class="text-center mb-4">
            <h2>OFFICIAL LEAVE APPROVAL SLIP</h2>
            <p class="text-muted">Generated by Online Leave Management System</p>
            <hr>
        </div>

        <div class="row mb-3">
            <div class="col-6"><strong>Employee/Student Name:</strong></div>
            <div class="col-6"><?php echo $data['fullname']; ?></div>
        </div>
        <div class="row mb-3">
            <div class="col-6"><strong>Role/Designation:</strong></div>
            <div class="col-6"><?php echo ucfirst($data['role']); ?></div>
        </div>
        <div class="row mb-3">
            <div class="col-6"><strong>Leave Type:</strong></div>
            <div class="col-6"><?php echo $data['leave_type']; ?></div>
        </div>
        <div class="row mb-3">
            <div class="col-6"><strong>Duration:</strong></div>
            <div class="col-6"><?php echo $data['from_date']; ?> to <?php echo $data['to_date']; ?></div>
        </div>
        <div class="row mb-3">
            <div class="col-6"><strong>Reason:</strong></div>
            <div class="col-6"><?php echo $data['reason']; ?></div>
        </div>
        <div class="row mb-3">
            <div class="col-6"><strong>Status:</strong></div>
            <div class="col-6 text-success fw-bold">APPROVED</div>
        </div>

        <div class="mt-5 d-flex justify-content-between">
            <div>
                <p>Date Generated: <?php echo date('d-m-Y'); ?></p>
            </div>
            <div class="text-center">
                <div class="seal">HOD SEAL</div>
                <p class="mt-2">Digital Signature Verified</p>
            </div>
        </div>
    </div>
    <div class="text-center mt-4 no-print">
        <button onclick="window.print()" class="btn btn-primary">Print Now</button>
        <button onclick="window.close()" class="btn btn-secondary">Close</button>
    </div>
</body>
</html>